#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT36XXX) += nt36xxx.o nt36xxx_fw_update.o nt36xxx_ext_proc.o
obj-$(CONFIG_TOUCHSCREEN_NT36XXX_MP_CTRLRAM) += nt36xxx_mp_ctrlram.o
